backend:
  name: git-gateway
  branch: master

media_folder: "public/images/products"
public_folder: "/images/products"

local_backend: true

collections:
  - name: "products"
    label: "Prodotti"
    folder: "src/content/products"
    create: true
    extension: "json"
    format: "json"
    slug: "{{name}}"
    identifier_field: "name"
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - label: "Categoria"
        name: "category"
        widget: "select"
        options:
          - { label: "Pantaloni", value: "pantaloni" }
          - { label: "Maglie", value: "maglie" }
          - { label: "Top", value: "top" }
          - { label: "Abiti", value: "abiti" }
          - { label: "Giacche", value: "giacche" }
          - { label: "Accessori", value: "accessori" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Taglie (es. S, M, L)", name: "sizes", widget: "string" }
      - {
          label: "Prezzo",
          name: "price",
          widget: "number",
          valueType: "float",
          step: 0.01,
          min: 0.01,
        }
      - { label: "Badge", name: "badge", widget: "string", required: false }
      - label: "Stile Badge"
        name: "badgeType"
        widget: "select"
        required: false
        options:
          - { label: "Blu", value: "default" }
          - { label: "Oro", value: "outline" }
